import { describe, it, beforeAll, afterAll, expect } from 'vitest';
import NotificationDAO from '../../dao/NotificationDAO.mjs';
import dayjs from 'dayjs';
import {
    setupTestDatabase,
    teardownTestDatabase,
    resetReports
} from '../setup.mjs';

describe('NotificationDAO', () => {
    beforeAll(async () => {
        await setupTestDatabase();
        await resetReports();
    });

    // Cleanup after all tests
    afterAll(async () => {
        await teardownTestDatabase();
    });

    describe('createNotification', () => {
        it('creates a new notification successfully', async () => {            
            const message = {
                reportId: 1,
                senderId: 4,
                receiverId: 1,
                text: 'This is a test notification from officer to citizen',
                channelId: 1
            };
            const now = new dayjs().toString();
            const result = await NotificationDAO.createNotification(message);

            expect(result.reportId).toBe(message.reportId);
            expect(result.sender.id).toBe(message.senderId);
            expect(result.receiver.id).toBe(message.receiverId);
            expect(result.text).toBe(message.text);
            expect(result.channel.id).toBe(message.channelId);
            expect(result.isRead).toBe(false);
            expect(result.sendAt.toString()).toBe(now);
        });
        it('creates a new notification successfully', async () => {            
            const message = {
                reportId: 1,
                senderId: null,
                receiverId: 1,
                text: 'This is a test notification from autogenerated messages',
                channelId: 1
            };
            const now = new dayjs().toString();
            const result = await NotificationDAO.createNotification(message);

            expect(result.reportId).toBe(message.reportId);
            expect(result.senderId).toBeUndefined();
        });
    });

    

    describe('setNotificationsAsRead', () => {
        it('marks a notification as read successfully for citizen', async () => {

            const userId = 1;
            const reportId = 1;

            const result = await NotificationDAO.setNotificationsAsRead(userId, reportId);

            expect(result).toBe(2);
        });

        it('marks a notification as read for non existing user', async () => {

            const userId = 999;
            const reportId = 1;

            const result = await NotificationDAO.setNotificationsAsRead(userId, reportId);


            expect(result).toBe(0);
        });
    }); 
    
    describe('createComment', () => {
        it('creates a new comment successfully', async () => {
            const message = {
                reportId: 1,
                senderId: 4,
                receiverId: 1,
                text: 'This is a test comment from officer to citizen'
            };
            const now = new dayjs().toString();
            const result = await NotificationDAO.createComment(message);

            expect(result.reportId).toBe(message.reportId);
            expect(result.sender.id).toBe(message.senderId);
            expect(result.receiver.id).toBe(message.receiverId);
            expect(result.text).toBe(message.text);
            // comment isRead is stored as integer 0 (unread) / 1 (read)
            expect(result.isRead).toBe(0);
            // sendAt exists and is a date-like value
            expect(result.sendAt).toBeDefined();
        });

        it('creates a new comment with null senderId', async () => {
            const message = {
                reportId: 1,
                senderId: null,
                receiverId: 1,
                text: 'This is a test autogenerated comment'
            };
            const now = new dayjs().toString();
            const result = await NotificationDAO.createComment(message);

            expect(result.reportId).toBe(message.reportId);
            // mapper returns Comment with sender === null
            expect(result.sender).toBeNull();
            expect(result.text).toBe(message.text);
        });
    });

    describe('setCommentsAsRead', () => {
        it('marks comments as read successfully for citizen', async () => {

            // create two comments to be marked as read
            await NotificationDAO.createComment({ reportId: 1, senderId: 4, receiverId: 1, text: 'c1' });
            await NotificationDAO.createComment({ reportId: 1, senderId: null, receiverId: 1, text: 'c2' });

            const userId = 1;
            const reportId = 1;

            const result = await NotificationDAO.setCommentsAsRead(userId, reportId);

            // There may be existing comments created by earlier tests; ensure at least the two we created were marked
            expect(result).toBeGreaterThanOrEqual(2);
        });

        it('marks comments as read for non existing user', async () => {

            const userId = 999;
            const reportId = 1;

            const result = await NotificationDAO.setCommentsAsRead(userId, reportId);

            expect(result).toBe(0);
        });
    }); 
});