import { describe, it, beforeAll, afterAll, expect } from 'vitest';
import NotificationDAO from '../../dao/NotificationDAO.mjs';
import dayjs from 'dayjs';
import {
    setupTestDatabase,
    teardownTestDatabase,
    resetReports
} from '../setup.mjs';

describe('NotificationDAO', () => {
    beforeAll(async () => {
        await setupTestDatabase();
        await resetReports();
    });

    // Cleanup after all tests
    afterAll(async () => {
        await teardownTestDatabase();
    });

    describe('createNotification', () => {
        it('creates a new notification successfully', async () => {            
            const message = {
                reportId: 1,
                senderId: 4,
                receiverId: 1,
                text: 'This is a test notification from officer to citizen',
                channelId: 1
            };
            const now = new dayjs().toString();
            const result = await NotificationDAO.createNotification(message);

            expect(result.reportId).toBe(message.reportId);
            expect(result.sender.id).toBe(message.senderId);
            expect(result.receiver.id).toBe(message.receiverId);
            expect(result.text).toBe(message.text);
            expect(result.channel.id).toBe(message.channelId);
            expect(result.isRead).toBe(false);
            expect(result.sendAt.toString()).toBe(now);
        });
        it('creates a new notification successfully', async () => {            
            const message = {
                reportId: 1,
                senderId: null,
                receiverId: 1,
                text: 'This is a test notification from autogenerated messages',
                channelId: 1
            };
            const now = new dayjs().toString();
            const result = await NotificationDAO.createNotification(message);

            expect(result.reportId).toBe(message.reportId);
            expect(result.senderId).toBeUndefined();
        });
    });

    

    describe('setNotificationsAsRead', () => {
        it('marks a notification as read successfully for citizen', async () => {

            const userId = 1;
            const reportId = 1;

            const result = await NotificationDAO.setNotificationsAsRead(userId, reportId);

            expect(result).toBe(2);
        });

        it('marks a notification as read for non existing user', async () => {

            const userId = 999;
            const reportId = 1;

            const result = await NotificationDAO.setNotificationsAsRead(userId, reportId);


            expect(result).toBe(0);
        });
    }); 
});