import "../styles/Message.css";
import dayjs from 'dayjs';

export default function Message(props) {
    const { message } = props;
    const formattedSendAt = message.sendAt ? dayjs(message.sendAt).format('DD/MM/YYYY HH:mm') : '';
    return (
        <div className="message-container" style={{ minWidth: message.sender ? '140px' : '250px' }}>
            <div className="message-content" style={{ fontStyle: message.sender ? '' : 'italic' }}>
                {message.text}
            </div>
            <div
                className={`message-bottom-row ${!message.sender ? '' : 'timestamp-alone'}`}
            >
                {!message.sender && (
                    <div className="message-autogenerated">
                        AUTOGENERATED
                    </div>
                )}

                <div className="message-timestamp">
                    {formattedSendAt}
                </div>
            </div>
        </div>
    );
}