import { Container, Row, Image } from "react-bootstrap";
import error from '../assets/error.png'
import "../styles/Message.css";

export default function Message(props){
    const { message } = props;
    const formattedSendAt = message.sendAt ? message.sendAt.slice(0, 16) : '';
    return (
        <div className="message-container" style={{ minWidth: message.sender.id ? '140px' : '250px' }}>
            <div className="message-content" style={{ fontStyle: message.sender.id ? '' : 'italic' }}>
                {message.text}
            </div>
            <div 
                className={`message-bottom-row ${!message.sender.id ? '' : 'timestamp-alone'}`}
            >
                {!message.sender.id && (
                    <div className="message-autogenerated">
                        AUTOGENERATED
                    </div>
                )}
                
                <div className="message-timestamp">
                    {formattedSendAt}
                </div>
            </div>
        </div>
    );
}